#!/usr/bin/env python3

import subprocess

import os

def list_env():
    curdir = subprocess.call("ls")
    curpath = subprocess.call("pwd", shell=True)
    #curpath = os.getcwd()
    #curdir = os.listdir(curpath)

    print(curpath)
    print(curdir)

    #print("The current directory is: " + curpath)
    #print("The contents of the dirctory is: " + curdir)


list_env()
